# Generated by Django 2.0.2 on 2018-03-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_build', '0003_appliances_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermiss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powerusage',
            fields=[
                ('energyusageid', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('sensorid', models.IntegerField()),
                ('endtimestamp', models.DateTimeField(blank=True, null=True)),
                ('usage', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'powerusage',
                'managed': False,
            },
        ),
    ]
