# Generated by Django 2.0.2 on 2018-03-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_build', '0004_powerusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livepowerusage',
            fields=[
                ('livepowerusageid', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('sensorids', models.CharField(max_length=200)),
                ('endtimestamp', models.DateTimeField(blank=True, null=True)),
                ('usage', models.FloatField()),
                ('cost', models.FloatField()),
            ],
            options={
                'db_table': 'livepowerusage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livewaterusage',
            fields=[
                ('livewaterusageid', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('sensorids', models.CharField(max_length=200)),
                ('endtimestamp', models.DateTimeField(blank=True, null=True)),
                ('usage', models.FloatField()),
                ('cost', models.FloatField()),
            ],
            options={
                'db_table': 'livewaterusage',
                'managed': False,
            },
        ),
    ]
